spring:
  datasource:
    url: jdbc:postgresql://sports-deploy-db.internal:5432/postgres
    username: postgres
    password: ffkfOobGyGyVyiv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
custom:
  genFileDirPath: C:\Users\hanjaehyun\Pictures\genFile